@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package themcbros.usefulmachinery.menu;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
