# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Mod Properties
mod_id=usefulmachinery
mod_name=Useful Machinery
mod_license=MIT License
mod_version=1.0.0
mod_group_id=net.themcbrothers
mod_authors=TheMCBrothers
mod_description=It adds simple machines for processing stuff

# Minecraft
minecraft_version=26.1
minecraft_version_range=[26.1)
minecraft_supported_versions=26.1

# NeoForge
neo_version=26.1.0.6-beta
neo_version_range=[26.1,)
loader_version_range=[11,)

# Dependencies
lib_version=26.1-10.0.0
lib_version_range=[26.1-10,)
foundation_version=26.1-1.0.0
foundation_version_range=[26.1-1.0.0,)
jei_version=29.1.0.16
jei_version_range=[29.1.0.16,)
#top_version=1.21_neo-12.0.3-5
#top_version_range=[1.21_neo-12.0.3-5,)
jade_id=7817285
jade_version_range=[26.0.6,)

# Publishing
archive_base=useful-machinery
artifact_type=release
github_repo=TheMCBrothers/Useful-Machinery
curse_project=355129
modrinth_project=AVW4n3h7
