modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/${github_repo}/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    updateJSONURL = "https://neoforge.curseupdate.com/${curse_project}/${mod_id}"
    displayURL = "https://themcbrothers.net/mods"
    logoFile = "logo.png"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "tmcb_lib"
    type = "required"
    versionRange = "${lib_version_range}"
    ordering = "NONE"
    side = "BOTH"
