modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
# issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="usefulmachinery" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Useful Machinery" #mandatory
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://themcbros.tk/" #optional
# logoFile="examplemod.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="TheMCBrothers" #optional
description='''
This is a mod that adds machines
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.usefulmachinery]] #optional
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.usefulmachinery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"