modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/TheMCBrothers/Useful-Machinery/issues"
license = "MIT License"

[[mods]]
    modId = "usefulmachinery"
    version = "${file.jarVersion}"
    displayName = "Useful Machinery"
    updateJSONURL = "https://forge.curseupdate.com/355129/usefulmachinery"
    displayURL = "https://themcbrothers.net/mods/usefulmachinery"
    logoFile = "logo.png"
    logoBlur = false
    authors = "TheMCBrothers"
    description = '''
    This is a mod that adds machines
    '''

[[dependencies.usefulmachinery]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulmachinery]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulmachinery]]
    modId = "tmcb_lib"
    mandatory = true
    versionRange = "${themcbroslib_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulmachinery]]
    modId = "usefulfoundation"
    mandatory = true
    versionRange = "${usefulfoundation_version_range}"
    ordering = "NONE"
    side = "BOTH"

[modproperties.usefulmachinery]
    catalogueItemIcon = "usefulmachinery:battery"
