modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
license="MIT License"
# issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="usefulmachinery" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Useful Machinery" #mandatory
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://themcbrothers.net/" #optional
# logoFile="examplemod.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="TheMCBrothers" #optional
description='''
This is a mod that adds machines
'''
[[dependencies.usefulmachinery]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulmachinery]]
    modId="tmcb_lib"
    mandatory=true
    versionRange="[1.19.4-3.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulmachinery]]
    modId="usefulfoundation"
    mandatory=true
    versionRange="[1.19.4-1.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulmachinery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
