modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT License"
# issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="usefulmachinery" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Useful Machinery" #mandatory
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://themcbrothers.net/" #optional
# logoFile="examplemod.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="TheMCBrothers" #optional
description='''
This is a mod that adds machines
'''
[[dependencies.usefulmachinery]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulmachinery]] #optional
    modId="tmcb_lib"
    mandatory=true
    versionRange="[1.19.2-2.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulmachinery]] #optional
    modId="usefulfoundation"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulmachinery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.3)"
    ordering="NONE"
    side="BOTH"
