@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.usefulmachinery.compat.jei.categories;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;