@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNullableByDefault
package net.themcbrothers.usefulmachinery.compat.jei.recipes;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNullableByDefault;