@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.usefulmachinery.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;