@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.usefulmachinery.compat.jei.categories;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;