on:
  push:
    branches-ignore:
      - '**-dev'
    paths-ignore:
      - '.github/**'
      - '**.md'
      - '**.txt'

permissions:
  contents: read

jobs:
  build:
    uses: TheMCBrothers/.github/.github/workflows/mod_ci.yml@main
