name: Java CI

on:
  push:
    branches-ignore:
      - '**-dev'
    paths-ignore:
      - '.github/**'
      - '**.md'
      - '**.txt'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: TheMCBrothers/.github/.github/workflows/mod_ci.yml@main
